apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  type: ClusterIP
  selector:
    service: backend-user
  ports:
    - port: 8080
      targetPort: 8080
