apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  type: ClusterIP
  selector:
    service: backend-feed
  ports:
    - port: 8080
      targetPort: 8080
