apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: codeballet/udacity-restapi-feed
          imagePullPolicy: Always  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m" 
          ports:
            - containerPort: 8080
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: AWS_MEDIA_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_MEDIA_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: POSTGRESS_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-password
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgress-username
                  key: POSTGRESS_USERNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
          