apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  type: NodePort
  ports:
    - port: 8100
      targetPort: 80
      nodePort: 31515
  selector:
    service: frontend
