version: "3"
services:
  reverseproxy:
    image: codeballet/udacity-reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: codeballet/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - POSTGRESS_USERNAME
      - POSTGRESS_PASSWORD
      - POSTGRESS_DB
      - POSTGRESS_HOST
      - AWS_REGION
      - AWS_PROFILE
      - AWS_MEDIA_BUCKET
      - JWT_SECRET
      - URL
  backend-feed:
    image: codeballet/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - POSTGRESS_USERNAME
      - POSTGRESS_PASSWORD
      - POSTGRESS_DB
      - POSTGRESS_HOST
      - AWS_REGION
      - AWS_PROFILE
      - AWS_MEDIA_BUCKET
      - JWT_SECRET
      - URL
  frontend:
    image: codeballet/udacity-c2-frontend
    ports:
      - 8100:80
